name: Build Backend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x BiblioBack/mvnw

      - name: Check code formatting
        run: |
          cd BiblioBack
          ./mvnw spotless:check

      - name: Run PMD analysis
        run: |
          cd BiblioBack
          ./mvnw pmd:check

      # faire une suppression ciblée SpotBugs + justification
      # - name: Run SpotBugs analysis
      #   run: |
      #     cd BiblioBack
      #     ./mvnw spotbugs:check

      - name: Run tests
        run: |
          cd BiblioBack
          ./mvnw test -B

      - name: Package application
        run: |
          cd BiblioBack
          ./mvnw package -DskipTests